### ISSUE TITLE
note official github repo

### ISSUE THREAD

**Issue by stevengj** [valandil/Cubature#1]
Hi, thanks for putting this up!  Note that there is now an "official" github repo of the cubature code:

https://github.com/stevengj/cubature

which has the full history, markdown documentation, etcetera.  The original (ab-initio.mit.edu) URL now redirects there.

**Comment by joeydumont** [comment]
And thank you for the heads up! I'll probably fork the official repo then, as we use CMake to build Cubature in some of our in-house codes.

**Comment by stevengj** [comment]
Note that the official repo already has a CMakeLists.txt (stevengj/cubature#2).  If there's anything missing from this, a PR would be welcome.

**Comment by joeydumont** [comment]
Oh, hadn't seen that. Will test in a couple of weeks.
